/*
 * SpacePixels
 *
 * Copyright (c)2020-2026, Petros Pissias.
 * See the LICENSE file included in this distribution.
 *
 * author: Petros Pissias <petrospis at gmail.com>
 *
 */

package eu.startales.spacepixels.util.reporting;

import javax.imageio.*;
import javax.imageio.metadata.*;
import javax.imageio.stream.*;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import java.awt.image.BufferedImage;

/**
 * Small ImageIO-based helper for writing animated GIF sequences used by report previews and blink visualizations.
 */
public class GifSequenceWriter {
    protected ImageWriter gifWriter;
    protected ImageWriteParam imageWriteParam;
    protected IIOMetadata imageMetaData;

    /**
     * Creates a new GifSequenceWriter.
     *
     * @param outputStream The ImageOutputStream to write to.
     * @param imageType    Usually BufferedImage.TYPE_BYTE_GRAY or TYPE_INT_RGB.
     * @param timeBetweenFramesMS Delay in milliseconds between frames.
     * @param loopContinuously Whether the GIF should loop infinitely.
     */
    public GifSequenceWriter(ImageOutputStream outputStream, int imageType, int timeBetweenFramesMS, boolean loopContinuously) throws IOException {
        // Find a GIF writer
        Iterator<ImageWriter> iter = ImageIO.getImageWritersBySuffix("gif");
        if (!iter.hasNext()) {
            throw new IIOException("No GIF Image Writers Exist");
        }
        gifWriter = iter.next();
        gifWriter.setOutput(outputStream);
        gifWriter.prepareWriteSequence(null);

        imageWriteParam = gifWriter.getDefaultWriteParam();
        ImageTypeSpecifier imageTypeSpecifier = ImageTypeSpecifier.createFromBufferedImageType(imageType);

        imageMetaData = gifWriter.getDefaultImageMetadata(imageTypeSpecifier, imageWriteParam);

        String metaFormatName = imageMetaData.getNativeMetadataFormatName();

        IIOMetadataNode root = (IIOMetadataNode) imageMetaData.getAsTree(metaFormatName);

        IIOMetadataNode graphicsControlExtensionNode = getNode(root, "GraphicControlExtension");
        // Delay time is in hundredths of a second (10ms units)
        graphicsControlExtensionNode.setAttribute("delayTime", Integer.toString(timeBetweenFramesMS / 10));
        graphicsControlExtensionNode.setAttribute("disposalMethod", "none");
        graphicsControlExtensionNode.setAttribute("userInputFlag", "FALSE");
        graphicsControlExtensionNode.setAttribute("transparentColorFlag", "FALSE");
        graphicsControlExtensionNode.setAttribute("transparentColorIndex", "0");

        IIOMetadataNode commentsNode = getNode(root, "CommentExtensions");
        commentsNode.setAttribute("CommentExtension", "Generated by SPV Tracker");

        if (loopContinuously) {
            IIOMetadataNode appEntensionsNode = getNode(root, "ApplicationExtensions");
            IIOMetadataNode child = new IIOMetadataNode("ApplicationExtension");
            child.setAttribute("applicationID", "NETSCAPE");
            child.setAttribute("authenticationCode", "2.0");

            int loop = 0; // 0 means loop continuously
            child.setUserObject(new byte[]{0x1, (byte) (loop & 0xFF), (byte) ((loop >> 8) & 0xFF)});
            appEntensionsNode.appendChild(child);
        }

        imageMetaData.setFromTree(metaFormatName, root);
    }

    public void writeToSequence(RenderedImage img) throws IOException {
        gifWriter.writeToSequence(new IIOImage(img, null, imageMetaData), imageWriteParam);
    }

    public void close() throws IOException {
        gifWriter.endWriteSequence();
    }

    private static IIOMetadataNode getNode(IIOMetadataNode rootNode, String nodeName) {
        int nNodes = rootNode.getLength();
        for (int i = 0; i < nNodes; i++) {
            if (rootNode.item(i).getNodeName().compareToIgnoreCase(nodeName) == 0) {
                return ((IIOMetadataNode) rootNode.item(i));
            }
        }
        IIOMetadataNode node = new IIOMetadataNode(nodeName);
        rootNode.appendChild(node);
        return node;
    }

    // =========================================================================
    // HELPER METHOD: Call this single method to do all the work!
    // =========================================================================
    public static void saveAnimatedGif(List<BufferedImage> frames, File outputFile, int delayMs) throws IOException {
        if (frames == null || frames.isEmpty()) return;

        ImageOutputStream output = new FileImageOutputStream(outputFile);

        // Initialize the writer using the format of the first frame
        GifSequenceWriter writer = new GifSequenceWriter(
                output,
                frames.get(0).getType(),
                delayMs,
                true // Loop continuously
        );

        // Write every frame to the file
        for (BufferedImage frame : frames) {
            writer.writeToSequence(frame);
        }

        writer.close();
        output.close();
    }
}
